//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmer.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> Count { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
