//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.ComponentsAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chicken
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chicken()
        {
            this.OrderChicken = new HashSet<OrderChicken>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Weight { get; set; }
        public string Age { get; set; }
        public Nullable<int> EggsInMonth { get; set; }
        public Nullable<int> CageId { get; set; }
        public Nullable<int> HealthId { get; set; }
        public Nullable<int> BreedId { get; set; }
        public byte[] PhotoChic { get; set; }
        public Nullable<int> StatusLifeId { get; set; }
    
        public virtual Breed Breed { get; set; }
        public virtual Cage Cage { get; set; }
        public virtual Health Health { get; set; }
        public virtual StatusLife StatusLife { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderChicken> OrderChicken { get; set; }
    }
}
